version: '3'
services:
  api:
    build:
      context: .
    volumes:
      - .:/usr/src/app  # Sincroniza tu proyecto local con el contenedor
      - /usr/src/app/node_modules  # Evita problemas con node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://usuario:password@db:5432/mi_base_de_datos
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5432:5432"