name: backend
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules

  db:
    build: db
    container_name: postdb
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: